### ISSUE TITLE
example vcfs not available?  

### ISSUE THREAD

**Issue by davidballi** [immune-health/antigen.garnish#99]
Receiving the below when trying to download example vcf.  Happening on EC2 and local machine.  Links expire?

```
1: In utils::download.file("http://get.rech.io/antigen.garnish_example.vcf",  :
  URL http://get.rech.io/antigen.garnish_example.vcf: cannot open destfile 'antigen.garnish_example.vcf', reason 'Permission denied'
2: In utils::download.file("http://get.rech.io/antigen.garnish_example.vcf",  :
  download had nonzero exit status
```

**Comment by andrewrech** [comment]
fixing now

**Comment by andrewrech** [comment]
there were deleted when we moved the test files to within the package repo, but they should remain for the examples, and I have replaced them

**Comment by davidballi** [comment]
the example output for the unit tests is also not available. Not seeing a hard-copy in the `clone_wars` branch, any other suggestions?

```
> dt <- data.table::fread("http://get.rech.io/antigen.garnish_example_output.txt") %>%
+     garnish_fitness %>%
+     .[, fitness_score := 5]
trying URL 'http://get.rech.io/antigen.garnish_example_output.txt'
Error in download.file(input, tmpFile, method = method, mode = "wb", quiet = !showProgress) :
  cannot open URL 'http://get.rech.io/antigen.garnish_example_output.txt'
In addition: Warning message:
In download.file(input, tmpFile, method = method, mode = "wb", quiet = !showProgress) :
  cannot open URL 'http://ihmvgkpeoiakxlajyewnrgxwtrtyevdmfzgdbjkmquaozqhbfgihmvgkpeoiaka.s3-website-us-east-1.amazonaws.com/antigen.garnish_example_output.txt': HTTP status was '404 Not Found'
```

**Comment by leeprichman** [comment]
I think we no longer use that file.  Is that the most recent version of the clone_wars branch?  Everything the unit tests require should be in the testdata folder.... I will spin a fresh instance and test now too.

**Comment by davidballi** [comment]
Based on the `git log`, I should be on the most recent commit:
```
commit 1f35fa8f97edb995473cc5d975cd0822cd1b2965
Author: Lee Richman <leepr@upenn.edu>
Date:   Thu May 3 14:25:14 2018 -0400
```

I am not seeing a testdata folder.

**Comment by leeprichman** [comment]
I'm booting a fresh instance now.  Testfiles should should be in inst/extdata/testdata.  There are no more data.table::fread calls on urls in the current unit tests.  is this from one of the manpage examples? If so I never edited those....woops

**Comment by leeprichman** [comment]
build and tests worked fine on a clean instance for me, but i couldnt find anywhere in the test files where it still runs fread on that defunct URL.  where was that listed? I'll remove it from whatever documentation its in and replace it with using the testdata embedded in the package now.  I wanted to move away from hosting a lot of the test data ourselves because i was having so many curl bugs and would time out even on an AWS machine sometimes.

**Comment by davidballi** [comment]
I think I made a mistake looking at unit tests from `master` on github when I had checked out `clone_wars` locally.  I found the inst/extdata/testdata on my local repo.  Outside of the README example, I think that should explain my confusion.  Go ahead and close this out.

**Comment by andrewrech** [comment]
Sorry about the trouble David -the tests being linked to a URL is the wrong way to do things, since you lose idempotency with respect to the installed package. Hopefully this will be better.

**Comment by davidballi** [comment]
Its all cool.  I do have a new question.  I have worked up [`garnish_slim()`](https://github.com/davidballi/antigen.garnish/blob/master/R/antigen.garnish_io.R) that takes `dt` from `garnish_affinity` and return the "core" features that I would assume a standard user would need at a minimum for each prediction ran (ie. the scores from mhcflurry, netMHC*, mhcnuggets, MHC, variant info, consensus scores, etc.) that is a little easier to parse than the full output.   The full length cDNA and peptide is good to have, but probably too much for any downstream peptide-MHC prediction analysis.

Trying to work through the unit tests now, but `antigen.garnish_example_affinity_output.txt` does not appear to have the following:

```
Error in `[.data.table`(dt, , ..cols_to_keep) :
  column(s) not found: mhcflurry_prediction_percentile, mhcnuggets_pred_lstm, mhcnuggets_pred_gru, best_netMHC, BLAST_A, iedb_score, min_DAI, fitness_score
```

Is this the wrong file or do I have to run `garnish_fitness` and others?   I have written `garnish_slim` to assume a user ran the full suite of predictions (regarldess of Class I, II or both ran).  Ideas?

**Comment by leeprichman** [comment]
You are correct that not all of those columns are in that table, glad someone dug through it and found this.  It looks like this test file was made a long time ago before additional functions were added to garnish_affinity.  I will add updating this one to my #TODO list.

Re table output: There are some columns that will not be present if for example ncbiblast is not installed.  As of right now all prediction tools must be installed to run, so assuming those are all there is a safe bet.  I will add those columns to that file tomorrow and bump the repo so that you can work with it.  Sorry for the trouble.

I think the easiest thing is to just go ahead and write with the assumption all columns are present.  I can then go back through the code base and make garnish_slim have the conditionals to deal with missing columns from different permutations of running the pipeline.

**Comment by leeprichman** [comment]
looks like the "antigen.garnish_PureCN_example_output.txt" file has all of the column names.  does that work for your purposes or should i add columns to the "antigen.garnish_example_affinity_output.txt" file.

**Comment by davidballi** [comment]
I'll use the PureCN_example_output.txt tonight and let you know.

**Comment by davidballi** [comment]
@leeprichman that file is missing `netMHCII` outputs:

```
Error in `[.data.table`(dt, , ..cols_to_keep) :
  column(s) not found: affinity(nM)_netMHCII, %Random_netMHCII
```

**Comment by leeprichman** [comment]
Totally lost track of this.  I will follow up on this asap. Why don't i make a new example output file with the maximum possible columns for you?

**Comment by davidballi** [comment]
@leeprichman, dont worry about making a new example output just for this test.  I was going to generate one when making a tutorial/vignette and use it for the unit tests.  

if different columns are need or not needed, I'll be happy to implement.
